window.Auth={
  init:async function(){
    await FB.init();
    if(FB.enabled){
      FB.auth.onAuthStateChanged(async u=>{
        if(!u){this.welcome();return}
        CC.user={uid:u.uid,name:u.displayName||'',email:u.email||'',isOwner:FB.isOwnerAuth(u)};
        try{
          const snap=await FB.db.collection('users').doc(u.uid).get();
          if(!snap.exists || !snap.data().username){ this.onboarding({name:u.displayName||'',username:'',email:u.email||'',uid:u.uid}); return; }
          CC.user={...CC.user,...await FB.ensureUser(u,snap.data()),isOwner:FB.isOwnerAuth(u)}; App.start();
        }catch(err){UI.toast(err.message);this.welcome()}
      });
    }else{let u=localStorage.getItem('cc_user');if(u){CC.user=JSON.parse(u);App.start()}else this.welcome()}
  },
  welcome(){authRoot.innerHTML=`<main class="auth"><section class="auth-card"><div class="auth-hero"><div class="brand">● CONNECT CAMPUS</div><h1>One campus. Connected people.</h1><p>Use your unique username or continue with Google.</p></div><div class="auth-form"><h2>Welcome</h2><div class="auth-actions"><button class="btn" onclick="Auth.login()">Sign in</button><button class="btn secondary" onclick="Auth.signup()">Create account</button></div><button class="btn google" onclick="Auth.google()">G Continue with Google</button></div></section></main>`},
  login(){authRoot.innerHTML=`<main class="auth"><section class="auth-card"><div class="auth-hero"><div class="brand">● CONNECT CAMPUS</div><h1>Welcome back.</h1></div><form class="auth-form" onsubmit="Auth.doLogin(event)"><h2>Sign in</h2><div class="field"><label>Username</label><input id="username" autocomplete="username" required></div><div class="field"><label>Password</label><input id="password" type="password" autocomplete="current-password" required></div><button class="link" type="button" onclick="Auth.forgot()">Forgot password?</button><div class="auth-actions"><button class="btn">Sign in</button><button class="btn secondary" type="button" onclick="Auth.signup()">Create account</button></div><button class="btn google" type="button" onclick="Auth.google()">G Continue with Google</button></form></section></main>`},
  signup(){authRoot.innerHTML=`<main class="auth"><section class="auth-card"><div class="auth-hero"><div class="brand">● CONNECT CAMPUS</div><h1>Create your account.</h1></div><form class="auth-form" onsubmit="Auth.doSignup(event)"><h2>Create account</h2><div class="field"><label>Full name</label><input id="name" required></div><div class="field"><label>Unique username</label><input id="username" pattern="[A-Za-z0-9._-]{3,24}" required><small>3–24 characters. Letters, numbers, . _ -</small></div><div class="field"><label>Email</label><input id="email" type="email" required></div><div class="field"><label>Password</label><input id="password" type="password" minlength="6" required></div><button class="btn">Continue</button><button class="btn google" type="button" onclick="Auth.google()">G Sign up with Google</button></form></section></main>`},
  async doLogin(e){e.preventDefault();try{if(FB.enabled){const mail=await FB.emailForUsername(username.value);await FB.auth.signInWithEmailAndPassword(mail,password.value)}else this.finish({uid:'local-'+username.value,name:username.value,username:username.value,roles:['student']})}catch(err){UI.toast(err.message)}},
  async doSignup(e){e.preventDefault();try{if(FB.enabled){if(!await FB.usernameAvailable(username.value)) throw new Error('Username is already taken.');let r=await FB.auth.createUserWithEmailAndPassword(email.value,password.value);await r.user.updateProfile({displayName:name.value});this.onboarding({name:name.value,username:username.value,email:email.value,uid:r.user.uid})}else this.onboarding({name:name.value,username:username.value,email:email.value,uid:'local-'+Date.now()})}catch(err){UI.toast(err.message)}},
  async google(){try{if(!FB.enabled){UI.toast('Add Firebase configuration to enable Google sign-in.');return}const p=new firebase.auth.GoogleAuthProvider();p.setCustomParameters({prompt:'select_account'});await FB.auth.signInWithPopup(p)}catch(e){UI.toast(e.message)}},
  forgot(){UI.modal('Reset password',`<div class="field"><label>Account email</label><input id="resetEmail" type="email"></div><button class="btn" onclick="Auth.reset()">Send reset link</button>`)},
  async reset(){try{if(FB.enabled)await FB.auth.sendPasswordResetEmail(resetEmail.value);UI.close();UI.toast('Password reset request sent')}catch(e){UI.toast(e.message)}},
  onboarding(u){authRoot.innerHTML=`<main class="auth"><section class="auth-card"><div class="auth-hero"><div class="brand">● CONNECT CAMPUS</div><h1>Set up your academic profile.</h1></div><form class="auth-form" onsubmit="Auth.finishProfile(event)"><div class="field"><label>Unique username</label><input id="onUsername" value="${u.username||''}" pattern="[A-Za-z0-9._-]{3,24}" required></div><div class="field"><label>Institution</label><input id="inst" required value="${CC.data.profile.institution||''}"></div><div class="field"><label>Department</label><input id="dept" required value="${CC.data.profile.department||''}"></div><div class="field"><label>Semester</label><input id="sem" required value="${CC.data.profile.semester||''}"></div><input id="onName" type="hidden" value="${u.name||''}"><button class="btn">Enter Connect Campus</button></form></section></main>`},
  async finishProfile(e){e.preventDefault();try{CC.data.profile={institution:inst.value,department:dept.value,semester:sem.value,username:onUsername.value.trim().toLowerCase()};CC.save();if(FB.enabled)await FB.ensureUser(FB.auth.currentUser,{...CC.data.profile,name:onName.value,username:onUsername.value});this.finish({uid:FB.enabled?FB.auth.currentUser.uid:'local-'+Date.now(),name:onName.value,username:onUsername.value,roles:FB.enabled&&FB.isOwnerCurrent()?['owner_admin']:['student'],isOwner:FB.enabled&&FB.isOwnerCurrent()})}catch(err){UI.toast(err.message)}},
  finish(u){CC.user={...u,roles:u.roles||['student']};if(!FB.enabled)localStorage.setItem('cc_user',JSON.stringify(CC.user));App.start()},
  async logout(){if(FB.enabled)await FB.auth.signOut();else localStorage.removeItem('cc_user');CC.user=null;appRoot.classList.add('hidden');authRoot.classList.remove('hidden');this.welcome()}
};
